version: "3"

services:
  backend:
    build: ./backend
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://db:3306/$DB_NAME",
          "spring.datasource.password" : "$DB_PASSWORD"
        }'
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8-debian
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD -e "SHOW DATABASES;"
      interval: 2s
      timeout: 2s
      retries: 10

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/node_modules:/app/node_modules:ro

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx:ro
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

volumes:
  oba-db-volume: